CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT UNIQUE NOT NULL, username VARCHAR(30) UNIQUE NOT NULL, coding_level VARCHAR(20) NOT NULL DEFAULT 'intermediate' CHECK(coding_level IN ('beginner','intermediate','advanced')), password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE problems (id BIGSERIAL PRIMARY KEY, programmers_id BIGINT UNIQUE NOT NULL, title TEXT NOT NULL, difficulty SMALLINT NOT NULL CHECK(difficulty BETWEEN 0 AND 5), category TEXT NOT NULL, accuracy NUMERIC(5,2), expected_minutes SMALLINT NOT NULL DEFAULT 30, url TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE user_solutions (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE, solved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(user_id,problem_id));
CREATE TABLE daily_recommendations (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE, recommended_date DATE NOT NULL DEFAULT CURRENT_DATE, position SMALLINT NOT NULL CHECK(position BETWEEN 1 AND 5), PRIMARY KEY(user_id,recommended_date,position), UNIQUE(user_id,recommended_date,problem_id));
CREATE TABLE discussions (id BIGSERIAL PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE, title VARCHAR(120) NOT NULL, content TEXT NOT NULL, views INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE comments (id BIGSERIAL PRIMARY KEY, discussion_id BIGINT NOT NULL REFERENCES discussions(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_solutions_user_date ON user_solutions(user_id,solved_at DESC);
CREATE INDEX idx_discussions_problem_date ON discussions(problem_id,created_at DESC);
