ALTER TABLE problems ADD COLUMN IF NOT EXISTS expected_minutes SMALLINT NOT NULL DEFAULT 30;
ALTER TABLE discussions ADD COLUMN IF NOT EXISTS views INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_discussions_views ON discussions(views DESC);
